### PR TITLE
Add back logging

### PR DESCRIPTION
**Pull request by blickly**
Add back the logging that @charansr added before to track things like sign-ups, sign-ins, and toggling the nametag visibility (I hope I've got that right).

Unfortunately, I wasn't able to figure out a good way to automate the testing of the logging.  It seems like the way it involves multiple URLs makes it hard to test in unit tests, but it also doesn't have any visible change to the UI, making it seemingly not a good fit for e2e testing with cypress either.

Any advice on how to manually inspect the mongodb instance to verify that the logging is working?

### CODE REVIEW

**Comment by Shaomei** [comment]
@charansr Can you described your approach to verify the success/correctness of the loggings?

**Comment by charansr** [comment]
> @charansr Can you described your approach to verify the success/correctness of the loggings?

Hello Shaomei, I would check the correctness of the loggings manually on my computer using MongoDB compass, which provides a GUI to look at the contents of a database manually. I would run the logging code and then check to see the new entries in MongoDB compass.

**Review by Shaomei — APPROVED** [review]
Thanks for adding it back!

@charansr this what do you think?

**Comment by charansr** [comment]
> Thanks for adding it back!
> 
> @charansr this what do you think?

The code looks great! Thank you so much, Mr.Lickly, for fixing this. For the code, I was just wondering where the timestamp would be logged. Or is that not necessary?

**Pull request merged**
